 # .streamlit/secrets.toml

# Replace with the ACTUAL public URL provided by ngrok or Cloudflare Tunnel
# Make sure it points to where your local_bot_runner.py is listening (e.g., port 5000)
# Example: BOT_API_URL = "https://abcdef12345.ngrok.io"
# Example: BOT_API_URL = "https://your-tunnel-name.trycloudflare.com"
# IMPORTANT: Do NOT include a trailing slash '/'



BOT_API_URL = "https://yearly-profound-crayfish.ngrok-free.app" 
# BOT_API_URL = "http://localhost:5000" 



BOT_API_KEY = "your_very_secret_api_key_123_abc" # <<<--- CHANGE THIS to match your backend .env file